# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GridIndex
                                 A QGIS plugin
 This generates a grid of rectangular polygons for map book page indexing.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-06
        copyright            : (C) 2025 by Kapil Dev Adhiakri
        email                : kapildevadk@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
def classFactory(iface):
    """Load GridIndexFeaturesPlugin class from file grid_index_features_plugin.
    :param iface: A QGIS interface instance.
    """
    from .grid_index_features_plugin import GridIndexFeaturesPlugin
    return GridIndexFeaturesPlugin(iface)