# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GridIndex
                                 A QGIS plugin
 This generates a grid of rectangular polygons for map book page indexing.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-06
        copyright            : (C) 2025 by Kapil Dev Adhiakri
        email                : kapildevadk@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from qgis.core import QgsProcessingProvider
from .grid_index_features_algorithm import GridIndexFeaturesAlgorithm

class GridIndexFeaturesProvider(QgsProcessingProvider):

    def loadAlgorithms(self, *args, **kwargs):
        self.addAlgorithm(GridIndexFeaturesAlgorithm())

    def id(self, *args, **kwargs):
        """The ID of your plugin, used for identifying the provider.
        
        This string should be unique and must not be changed within a plugin
        once released.
        """
        return 'grid_index_features'

    def name(self, *args, **kwargs):
        """The human friendly name of your plugin in Processing.
        
        This string should be as short as possible.
        """
        return self.tr('Grid Index')

    def longName(self, *args, **kwargs):
        """The human friendly long name of your plugin in Processing.
        
        This string can be longer than name.
        """
        return self.tr('Grid Index')

    def icon(self):
        """Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from qgis.PyQt.QtGui import QIcon
        import os
        
        # Construct the full path to the icon file
        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        return QIcon(icon_path)