# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GridIndex
                                 A QGIS plugin
 This generates a grid of rectangular polygons for map book page indexing.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-06
        copyright            : (C) 2025 by Kapil Dev Adhiakri
        email                : kapildevadk@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from qgis.core import QgsApplication
from .grid_index_features_provider import GridIndexFeaturesProvider

class GridIndexFeaturesPlugin:
    """
    Main QGIS Plugin class.
    This class handles the registration of the Processing provider
    when the plugin is loaded and its removal when the plugin is unloaded.
    """
    def __init__(self, iface):
        """
        Constructor.
        :param iface: An interface instance that will be passed to this class
            which provides access to the QGIS GUI.
        """
        self.iface = iface
        self.provider = None

    def initGui(self):
        """Called when the plugin is loaded into QGIS."""
        # Create an instance of our Processing provider
        self.provider = GridIndexFeaturesProvider()
        # Add the provider to the QGIS Processing registry
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        """Called when the plugin is unloaded from QGIS."""
        # Remove the provider from the QGIS Processing registry
        if self.provider:
            QgsApplication.processingRegistry().removeProvider(self.provider)
        self.provider = None